language: node_js
node_js:
  - "stable"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm test

install:
  - npm install

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  app: react-tic-tac-toe